--return require("sidebar-nvim").setup({
--	open = true,
--	side= "left",
--	initial_width=30,
--	sections={"datetime","git","diagnostics","files", "symbols"},
--	section_separator = {"","",""},
--	    ["git"] = {
--        icon = "",
--    },
--	    datetime = {
--        icon = "",
--        format = "%a %b %d, %H:%M",
--    },
--	    ["diagnostics"] = {
--        icon = "",
--    },
--	   symbols = {
--        icon = "ƒ",
--    },
--	    files = {
--        icon = "",
--        show_hidden = true,
--        ignored_paths = {"%.git$"}
--    }
--})
